// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML;

namespace Camera_RecordML.Model
{
    public class ConsumeModel
    {
        private static PredictionEngine<ModelInput, ModelOutput> PredictionEngine;
        public ConsumeModel()
        {
            PredictionEngine = CreatePredictionEngine();
        }

        // For more info on consuming ML.NET models, visit https://aka.ms/mlnet-consume
        // Method for consuming model in your app
        public ModelOutput Predict(ModelInput input)
        {
            ModelOutput result = PredictionEngine.Predict(input);
            return result;
        }

        public PredictionEngine<ModelInput, ModelOutput> CreatePredictionEngine()
        {
            // Create new MLContext
            MLContext mlContext = new MLContext();

            // Load model & create prediction engine

            string modelPath = @"MLModel.zip";
            ITransformer mlModel = mlContext.Model.Load(modelPath, out var modelInputSchema);
            var predEngine = mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);

            return predEngine;
        }
    }
}
